export interface StickerSegment {
  id: string;
  dataUrl: string; // The segmented image as a base64 PNG
  originalX: number;
  originalY: number;
  width: number;
  height: number;
  name: string; // Generated by AI or default
  isNaming: boolean;
}

export interface ProcessingStatus {
  stage: 'idle' | 'analyzing_layout' | 'segmenting' | 'ai_naming' | 'complete';
  progress: number;
  message: string;
}
